### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by n3ps** [n3ps/json-schema-to-jsdoc#21]
With the recent set of changes, the npm package version is ready to be bumped. I propose 1.0.0 since it has considerably more features than my first iteration.

@brettz9 do you have anything else you wanted to include?

**Comment by brettz9** [comment]
I think it's fine for 1.0.0 now, though maybe having the Travis checks in #22 passing first would give a little extra assurance that everything is in order before releasing.

As far as new features, I still hope to offer a `maxLength` option and add array property support, but those could be added as minor bumps without any breaking changes (unless you wanted `maxLength` on by default in which case it would be a minor breaking change).

I guess there is one feature that I should probably see about working on first if you wanted to hold for it since I think you may want to go with it and replace the old behavior (or at least make it the default)--changing the nested property syntax to match the jsdoc docs (e.g., `@property anObjectProp.aNestedProp` instead of `@property .aNestedProp`). Of course, it could always be added, assuming made ready, as a version 2.0 release if you preferred.

**Comment by n3ps** [comment]
I can hold off for nested prop syntax and maxLength if they're not too hard to implement. 

I'm sure though if a maxLength should be on by default though. For example, if some user has their max cols way below our default.

**Comment by brettz9** [comment]
> I can hold off for nested prop syntax and maxLength if they're not too hard to implement.

This is high on my current priority list, but please don't hold off if it ends up taking longer than you want. I have some health/fatigue issues, so cannot be too reliable. The `maxLength` is not trivial but also don't expect it to be too bad. I haven't looked too carefully at how easy nested prop syntax would be, but also wouldn't think it should be too hard. Plan to work on these today.

> I'm sure though if a maxLength should be on by default though. For example, if some user has their max cols way below our default.

I guess you mean you're *not* sure it should be on by default (because someone might not want wrapping if the wrapping ends up still too large (or small) for their tastes)?

**Comment by n3ps** [comment]
Of course, no rush or pressure. I'll get the Travis stuff in.

Yeah, sometimes my typing and thoughts aren't in sync 😄

**Comment by brettz9** [comment]
> Of course, no rush or pressure. I'll get the Travis stuff in.

Cool. I submitted #23 and will look to do a husky PR next I think. I expect the `maxLength` to take some more time, though I do already have docs and a test for it as well as a bit of code.
 
> Yeah, sometimes my typing and thoughts aren't in sync 😄

I hear you on that for myself!
